from Net import resNet as myresnet, CNN, resNet18, resNet34, resNet50, resNet101, resNet152
from train_resnet import train
import matplotlib.pyplot as plt

testID = 18

res = myresnet(1,2)
res18 = resNet18(1,2)
res34 = resNet34(1,2)
res50 = resNet50(1,2)
res101 = resNet101(1,2)
res152 = resNet152(1,2)

R18_trainl, R18_loss, R18_acc, R18_f1, R18_iou, R18_recall = train(res18, 10, 3e-6, "./img/images/", epochs=20, name=f"resnet18_{testID}")
R34_trainl, R34_loss, R34_acc, R34_f1, R34_iou, R34_recall = train(res34, 10, 3e-6, "./img/images/", epochs=20, name=f"resnet34_{testID}")
R50_trainl, R50_loss, R50_acc, R50_f1, R50_iou, R50_recall = train(res50, 10, 3e-6, "./img/images/", epochs=20, name=f"resnet50_{testID}")
R101_trainl, R101_loss, R101_acc, R101_f1, R101_iou, R101_recall = train(res101, 10, 3e-6, "./img/images/", epochs=20, name=f"resnet101_{testID}")
R152_trainl, R152_loss, R152_acc, R152_f1, R152_iou, R152_recall = train(res152, 10, 3e-6, "./img/images/", epochs=20, name=f"resnet152_{testID}")
Rmy_trainl, Rmy_loss, Rmy_acc, Rmy_f1, Rmy_iou, Rmy_recall = train(res, 10, 3e-6, "./img/images/", epochs=20, name=f"myresnet_{testID}")

# show results
plt.clf()
plt.plot(R18_loss ,label="R18_loss", color='red')
plt.plot(R34_loss, label="R34_loss", color='blue')
plt.plot(R50_loss, label="R50_loss", color='green')
plt.plot(R101_loss, label="R101_loss", color='cyan')
plt.plot(R152_loss, label="R152_loss", color='yellow')
plt.plot(Rmy_loss, label="Rmy_loss", color='black')
plt.grid(True)
plt.legend()
plt.xticks(range(0, len(Rmy_trainl), 5))
plt.title("resnet-loss")
plt.savefig(f"plt/_{testID}/resnet_loss-versus_{testID}.png")
plt.close()

plt.clf()
plt.plot(R18_acc ,label="R18_acc", color='red')
plt.plot(R34_acc, label="R34_acc", color='blue')
plt.plot(R50_acc, label="R50_acc", color='green')
plt.plot(R101_acc, label="R101_acc", color='cyan')
plt.plot(R152_acc, label="R152_acc", color='yellow')
plt.plot(Rmy_acc, label="Rmy_acc", color='black')
plt.grid(True)
plt.legend()
plt.xticks(range(0, len(Rmy_trainl), 5))
plt.title("resnet-acc")
plt.savefig(f"plt/_{testID}/resnet_acc-versus_{testID}.png")
plt.close()

plt.clf()
plt.plot(R18_f1 ,label="R18_f1", color='red')
plt.plot(R34_f1, label="R34_f1", color='blue')
plt.plot(R50_f1, label="R50_f1", color='green')
plt.plot(R101_f1, label="R101_f1", color='cyan')
plt.plot(R152_f1, label="R152_f1", color='yellow')
plt.plot(Rmy_f1, label="Rmy_f1", color='black')
plt.grid(True)
plt.legend()
plt.xticks(range(0, len(Rmy_trainl), 5))
plt.title("resnet-f1")
plt.savefig(f"plt/_{testID}/resnet_f1-versus_{testID}.png")
plt.close()

plt.clf()
plt.plot(R18_recall ,label="R18_recall", color='red')
plt.plot(R34_recall, label="R34_recall", color='blue')
plt.plot(R50_recall, label="R50_recall", color='green')
plt.plot(R101_recall, label="R101_recall", color='cyan')
plt.plot(R152_recall, label="R152_recall", color='yellow')
plt.plot(Rmy_recall, label="Rmy_recall", color='black')
plt.grid(True)
plt.legend()
plt.xticks(range(0, len(Rmy_trainl), 5))
plt.title("resnet-recall")
plt.savefig(f"plt/_{testID}/resnet_recall-versus_{testID}.png")
plt.close()

# cnn = CNN(1,2)

# R_trainl, R_loss, R_acc, R_f1, R_iou, R_recall = train(res, 10, 1e-5, "./img/images/", epochs=30, name=f"resnet_{testID}")
# C_trainl, C_loss, C_acc, C_f1, C_iou, C_recall = train(cnn, 32, 2e-5, "./img/images/", epochs=30, name=f"cnn_{testID}")


# show results
# plt.clf()
# plt.plot(R_trainl ,label="train_loss", color='red')
# plt.plot(R_loss, label="test_loss", color='blue')
# plt.grid(True)
# plt.legend()
# plt.xticks(range(0, len(R_trainl), 5))
# plt.title("resnet-loss")
# plt.savefig(f"plt/_{testID}/resnet-loss_{testID}.png")
# plt.close()

# plt.clf()
# plt.plot(R_f1 ,label="test_f1", color='red')
# plt.grid(True)
# plt.legend()
# plt.xticks(range(0, len(R_trainl), 5))
# plt.title("resnet-f1")
# plt.savefig(f"plt/_{testID}/resnet-f1_{testID}.png")
# plt.close()

# plt.clf()
# plt.plot(R_iou ,label="resnet_iou", color='red')  
# plt.grid(True)
# plt.legend()
# plt.xticks(range(0, len(R_trainl), 5))
# plt.title("resnet-iou")
# plt.savefig(f"plt/_{testID}/resnet-iou_{testID}.png")
# plt.close()

# plt.clf()
# plt.plot(R_acc ,label="resnet_acc", color='red')
# plt.grid(True)
# plt.legend()
# plt.xticks(range(0, len(R_trainl), 5))
# plt.title("resnet-acc")
# plt.savefig(f"plt/_{testID}/resnet-acc_{testID}.png")
# plt.close()

# plt.clf()
# plt.plot(R_recall ,label="resnet_recall", color='red')
# plt.grid(True)
# plt.legend()
# plt.xticks(range(0, len(R_trainl), 5))
# plt.title("resnet-recall")
# plt.savefig(f"plt/_{testID}/resnet-recall_{testID}.png")
# plt.close()

# from test_model import test_model, test_res_model

# for i in range(1, 6):
#     test_res_model(res, f"./totest/images/benign ({i}).png", f"test{testID}_{(i-1)*2+1}")     
#     test_res_model(res, f"./totest/images/malignant ({i}).png", f"test{testID}_{(i-1)*2+2}")
# show cnn
# plt.clf()
# plt.plot(C_trainl ,label="train_loss", color='red')
# plt.plot(C_loss, label="test_loss", color='blue')
# plt.grid(True)
# plt.legend()
# plt.xticks(range(0, len(C_trainl), 5))
# plt.title("CNN-loss")
# plt.savefig(f"plt/_{testID}/CNN-loss_{testID}.png")
# plt.close()

# plt.clf()
# plt.plot(C_f1 ,label="CNN_f1", color='red')
# plt.grid(True)
# plt.legend()
# plt.xticks(range(0, len(C_trainl), 5))
# plt.title("CNN-f1")
# plt.savefig(f"plt/_{testID}/CNN-f1_{testID}.png")
# plt.close()

# plt.clf()
# plt.plot(C_iou ,label="CNN_iou", color='red')  
# plt.grid(True)
# plt.legend()
# plt.xticks(range(0, len(C_trainl), 5))
# plt.title("CNN-iou")
# plt.savefig(f"plt/_{testID}/CNN-iou_{testID}.png")
# plt.close()

# plt.clf()
# plt.plot(C_acc ,label="CNN_acc", color='red')
# plt.grid(True)
# plt.legend()
# plt.xticks(range(0, len(C_trainl), 5))
# plt.title("CNN-acc")
# plt.savefig(f"plt/_{testID}/CNNt-acc_{testID}.png")
# plt.close()

# plt.clf()
# plt.plot(C_recall ,label="CNN_recall", color='red')
# plt.grid(True)
# plt.legend()
# plt.xticks(range(0, len(C_trainl), 5))
# plt.title("CNN-recall")
# plt.savefig(f"plt/_{testID}/CNN-recall_{testID}.png")
# plt.close()